### ISSUE TITLE
Few of the files are in root directory not in c,cpp or js folder

### ISSUE THREAD

**Issue by ShubhraSuman** [jvm-coder/Hacktoberfest2022_aakash#148]
<img width="1440" alt="Screenshot 2022-10-08 at 10 58 08 AM 1" src="https://user-images.githubusercontent.com/53232818/194690536-5f832c56-620e-4d33-9e69-b4e3420156b9.png">

**Comment by ShubhraSuman** [comment]
can u assign it to me

**Comment by jvm-coder** [comment]
Sorry, the repository has been excluded from hacktoberfest, the reason is not known yet.
