### ISSUE TITLE
Centre the clock and add background colour

### ISSUE THREAD

**Issue by Akshitha2106** [jvm-coder/Hacktoberfest2022_aakash#285]
Respected sir I want to centre the position of the clock and add a background colour for clock website to lock more better. Sir please assign me this issue under hacktoberfest.

**Comment by Akshitha2106** [comment]
Respected sir(@jvm-coder ) please assign me this issue under hacktoberfest .

**Comment by jvm-coder** [comment]
Sorry, the repository has been excluded from hacktoberfest.
