### ISSUE TITLE
Add hover effect on buttons in budget app

### ISSUE THREAD

**Issue by Akshitha2106** [jvm-coder/Hacktoberfest2022_aakash#286]
Respected sir, please assign me this issue under hacktoberfest.

**Comment by Manishgupta200** [comment]
I would like to work on that issue. So, assign it to me.

**Comment by Akshitha2106** [comment]
Respected sir(@Hacktoberfest2022_aakash), please assign me this issue under hacktoberfest.

**Comment by jvm-coder** [comment]
Thanks for showing interest but the repository has been excluded from hacktoberfest.
