### ISSUE TITLE
Min-Max ordered pairs of subarray of a sequence

### ISSUE THREAD

**Issue by HKRcodes** [jvm-coder/Hacktoberfest2022_aakash#320]
Using this code, you can read a sequence of numbers and find the ordered pair (minimum value in subarray, maximum value in subarray) for the subarrays having user given size within the sequence length. We will get a vector having these ordered pairs.
Each new subarray is considered by releasing the first element in the previous subarray and taking in the next element after the previous subarray.

harikrishnanus2002@gmail.com

**Comment by shahrushi2003** [comment]
Please assign this issue to me.

**Comment by akshat2203** [comment]
hello @HKRcodes can you assign me this task..?
